language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Memoize"); Pkg.test("Memoize"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Memoize")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
